// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: client.sql

package repository

import (
	"context"
)

const DeleteClient = `-- name: DeleteClient :exec
DELETE FROM user_account WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, DeleteClient, id)
	return err
}

const GetClient = `-- name: GetClient :one
SELECT id,name,email FROM user_account WHERE id = $1
`

type GetClientRow struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) GetClient(ctx context.Context, id int32) (GetClientRow, error) {
	row := q.db.QueryRow(ctx, GetClient, id)
	var i GetClientRow
	err := row.Scan(&i.ID, &i.Name, &i.Email)
	return i, err
}

const GetRoleClient = `-- name: GetRoleClient :many
SELECT id_role FROM user_role WHERE id_user = $1
`

func (q *Queries) GetRoleClient(ctx context.Context, idUser int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, GetRoleClient, idUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id_role int32
		if err := rows.Scan(&id_role); err != nil {
			return nil, err
		}
		items = append(items, id_role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListClient = `-- name: ListClient :many
SELECT id,name,email FROM user_account
`

type ListClientRow struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) ListClient(ctx context.Context) ([]ListClientRow, error) {
	rows, err := q.db.Query(ctx, ListClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientRow{}
	for rows.Next() {
		var i ListClientRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateClient = `-- name: UpdateClient :one
UPDATE user_account SET 
	name = $2, 
	email = $3, 
	password = CASE
		WHEN $4 IS NULL OR TRIM($4) = '' THEN password
		ELSE $4
	END
WHERE id = $1 RETURNING id, name, email, password, created_at
`

type UpdateClientParams struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, UpdateClient,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
