// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OtpToken struct {
	ID        int32     `json:"id"`
	Code      string    `json:"code"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type UserAccount struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}

type UserProfile struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	Age       pgtype.Int4 `json:"age"`
	Phone     pgtype.Int4 `json:"phone"`
	District  pgtype.Text `json:"district"`
	City      pgtype.Text `json:"city"`
	Country   pgtype.Text `json:"country"`
	CreatedAt time.Time   `json:"created_at"`
}
