// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOTP(ctx context.Context, arg CreateOTPParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteOTP(ctx context.Context, email string) error
	DeleteProfile(ctx context.Context, id int32) error
	FindEmail(ctx context.Context, email string) (FindEmailRow, error)
	FindOTP(ctx context.Context, code string) (FindOTPRow, error)
	FindOtpByEmail(ctx context.Context, arg FindOtpByEmailParams) (int64, error)
	GetUser(ctx context.Context, id int32) (GetUserRow, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
}

var _ Querier = (*Queries)(nil)
