// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error)
	DeleteOTP(ctx context.Context, email string) error
	FindEmail(ctx context.Context, email string) (UserAccount, error)
	FindOTP(ctx context.Context, code string) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UserAccount, error)
}

var _ Querier = (*Queries)(nil)
