// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOTP(ctx context.Context, arg CreateOTPParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAccount(ctx context.Context, id int32) error
	DeleteOTP(ctx context.Context, email string) error
	FindEmail(ctx context.Context, email string) (FindEmailRow, error)
	FindOTP(ctx context.Context, code string) (FindOTPRow, error)
	FindOtpByEmail(ctx context.Context, arg FindOtpByEmailParams) (int64, error)
	GetProfile(ctx context.Context, id int32) (GetProfileRow, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
