// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package repository

import (
	"context"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO user_account(name,email,password) VALUES ($1,$2,$3) RETURNING id, name, email, password, created_at
`

type CreateUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, CreateUser, arg.Name, arg.Email, arg.Password)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const FindEmail = `-- name: FindEmail :one
SELECT id, name, email, password, created_at FROM user_account WHERE email = $1 LIMIT 1
`

func (q *Queries) FindEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, FindEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const UpdateUser = `-- name: UpdateUser :one
UPDATE user_account SET name=$2, email=$3, password=$4 WHERE id = $1 RETURNING id, name, email, password, created_at
`

type UpdateUserParams struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, UpdateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
