// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: otp.sql

package repository

import (
	"context"
)

const CreateOTP = `-- name: CreateOTP :exec
INSERT INTO otp_token(code,email) VALUES ($1,$2)
`

type CreateOTPParams struct {
	Code  string `json:"code"`
	Email string `json:"email"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) error {
	_, err := q.db.Exec(ctx, CreateOTP, arg.Code, arg.Email)
	return err
}

const DeleteOTP = `-- name: DeleteOTP :exec
DELETE FROM otp_token WHERE email = $1
`

func (q *Queries) DeleteOTP(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, DeleteOTP, email)
	return err
}

const FindOTP = `-- name: FindOTP :one
SELECT id, email FROM otp_token WHERE code = $1
`

type FindOTPRow struct {
	ID    int32  `json:"id"`
	Email string `json:"email"`
}

func (q *Queries) FindOTP(ctx context.Context, code string) (FindOTPRow, error) {
	row := q.db.QueryRow(ctx, FindOTP, code)
	var i FindOTPRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const FindOtpByEmail = `-- name: FindOtpByEmail :one
SELECT COUNT(*) FROM otp_token WHERE code = $1 AND email = $2
`

type FindOtpByEmailParams struct {
	Code  string `json:"code"`
	Email string `json:"email"`
}

func (q *Queries) FindOtpByEmail(ctx context.Context, arg FindOtpByEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, FindOtpByEmail, arg.Code, arg.Email)
	var count int64
	err := row.Scan(&count)
	return count, err
}
