CREATE SCHEMA IF NOT EXISTS "public";

CREATE  TABLE "public".otp_token ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
	code                 varchar DEFAULT 10 NOT NULL  ,
	email                varchar DEFAULT 100 NOT NULL  ,
	created_at           timestamptz DEFAULT CURRENT_DATE NOT NULL  ,
	CONSTRAINT pk_otp_token PRIMARY KEY ( id )
 );

CREATE  TABLE "public".user_account ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
	name                 varchar(100)  NOT NULL  ,
	email                varchar(100)  NOT NULL  ,
	"password"           varchar(100)  NOT NULL  ,
	created_at           timestamptz DEFAULT CURRENT_TIMESTAMP   ,
	CONSTRAINT pk_user_account PRIMARY KEY ( id )
 );

CREATE  TABLE "public".user_profile ( 
	id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY  ,
	user_id              integer  NOT NULL  ,
	age                  integer    ,
	phone                integer    ,
	district             varchar(100)    ,
	city                 varchar(100)    ,
	country              varchar(100)    ,
	created_at           timestamptz DEFAULT CURRENT_TIMESTAMP   ,
	CONSTRAINT pk_user_profile PRIMARY KEY ( id )
 );

ALTER TABLE "public".user_profile ADD CONSTRAINT fk_user_profile_user_account FOREIGN KEY ( user_id ) REFERENCES "public".user_account( id ) ON DELETE CASCADE;
